name: eeats
description: "A new Flutter project."

publish_to: 'none'

# 퍼블리싱 완료
version: 1.2.0+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  go_router: ^14.3.0
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/core/eeats_app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/core/
    - assets/icon/navigator/
    - assets/icon/meal/
    - assets/icon/alarm/
    - assets/icon/suggest/
    - assets/icon/my/
    - assets/images/core/

  fonts:
    - family: pretendard
      fonts:
        - asset: assets/font/pretendard_semibold.otf
          weight: 600
        - asset: assets/font/pretendard_medium.otf
          weight: 500
        - asset: assets/font/pretendard_regular.otf
          weight: 400
