Map<String, String> allergyData = {
  "EGGS" : "난류",
  "DAIRY" : "우유",
  "BUCKWHEAT" : "메밀",
  "PEANUTS" : "땅콩",
  "SOY" : "대두",
  "WHEAT" : "밀",
  "MACKEREL" : "고등어",
  "CRAB" : "게",
  "SHRIMP" : "새우",
  "PORK" : "돼지고기",
  "PEACH" : "복숭아",
  "TOMATO" : "토마토",
  "SULPHITES" : "아황산류",
  "WALNUTS" : "호두",
  "CHICKEN" : "닭고기",
  "BEEF" : "소고기",
  "SQUID" : "오징어",
  "SHELLFISH" : "조개류",
  "PINE_NUTS" : "잣",
};
